### ISSUE TITLE
Virtual keyboard

### ISSUE THREAD

**Issue by greatawesome** [JinShil/BlazorWebView#11]
Does the underlying WebKitGTK provide an on-screen keyboard, or would the application need to provide its own? I'd be interested in whether BlazorWebView would work for a touchscreen embedded device.

**Comment by JinShil** [comment]
BlazorWebView works fine with touchscreens, however, what specific touchscreen features and gestures are supported would depend on the operating system and WebKitGTK, so you'll have to direct such questions to those communities for details.

I am not aware of an on-screen keyboard for WebKitGTK.  Typically, that would be something provided by the operating system, or a separate software package built for the operating system (e.g. wvkbd, matchbox-keyboard, onboard, etc.).  It is possible to build your own on-screen keyboard into your application using Blazor.  I have created Blazor applications for embedded touchscreen devices that run Linux, and that is how I have chosen to do it because the on-screen keyboard features of the embedded operating system just don't work quite right (e.g. appearing when a textbox receives focus).  So, I suggest just using Blazor to make your own on-screen keyboard and embed it into your application in whatever way suits your use case.
